name: beebusy_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  built_value: ^8.1.4
  built_collection: ^5.1.1
  dio: ^4.0.4
  intl: ^0.17.0-nullsafety.2
  get: ^4.6.1
  flutter_localizations:
    sdk: flutter
  async: ^2.4.2
  get_storage: ^2.0.3
  eva_icons_flutter: ^3.1.0
  percent_indicator: ^3.4.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  overlay_group_avatar: ^0.0.2
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4
  analyzer: ^3.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/.
    - images/vector/.
    - images/raster/.
    - icons/

  fonts:
    - family: jakarta
      fonts:
        - asset: icons/jarakrta.ttf

#see https://github.com/google/built_value.dart/issues/923