version: '3.1'

services:

    db:
        container_name: beebusy_db
        image: postgres:13
        restart: always
        networks:
            - beebusy-backend
        volumes:
            - ./db/data:/var/lib/postgresql/data
            - ./db/entrypoint:/docker-entrypoint-initdb.d/
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    server:
        container_name: beebusy_server
        restart: always
        build: ../
        image: beebusy_server
        depends_on: 
            - db
        environment:
            DB_HOST: db
            DB_PORT: ${DB_PORT}
            DB_USER: ${DB_USER}
            DB_PW: ${DB_PASSWORD}
            DB_NAME: postgres
        ports: 
            - ${BACKEND_PORT}:80
        networks:
            - beebusy-backend
        entrypoint: >-
            bash -c "
                pub run aqueduct db upgrade
                /usr/bin/dart --no-sound-null-safety bin/main.dart
            "

    adminer:
        image: adminer
        restart: always
        depends_on:
            - db
        networks:
            - beebusy-backend
        ports:
            - 8080:8080

networks: 
    beebusy-backend: